### ISSUE TITLE
Thick black borders while using Kwin as WM

### ISSUE THREAD

**Issue by ryu-ketsueki** [paullinuxthemer/Mc-OS-themes#24]
This theme looks perfect alongside Kvantum Mojave theme in KDE or another Qt DE, but black borders appear if you are using Kwin as Window Manager, the default for Plasma 5. It seems to be happening with all themes.
![image](https://user-images.githubusercontent.com/39316730/48070661-891a3780-e1bf-11e8-9b1e-8a0240177fb0.png)

**Comment by pizzadude** [comment]
same issue here

**Comment by pizzadude** [comment]
@ryu-ketsueki I ended up using https://store.kde.org/p/1013714 instead as the gtk theme

**Comment by ryu-ketsueki** [comment]
> @ryu-ketsueki I ended up using https://store.kde.org/p/1013714 instead as the gtk theme

It is not as nice as McOS Mojave Dark

**Comment by Vistaus** [comment]
Same issue here. Please @paullinuxthemer, could you look into this?

**Comment by coenvl** [comment]
Even though this issue is closed, the issue also occurred to me when switching to i3 as a wm.

After a little digging around I found that the `box-shadow` property of the .csd classes are responsible. For example this line:

https://github.com/paullinuxthemer/Mc-OS-themes/blob/fcd7d8ec7f4ea1bc8a4f9c4dd695702c7a76528b/Mc-OS-CTLina-Gnome-Dark-1.3.2/gtk-3.0/gtk-dark.css#L11121

If you change this shadow to `0` or `none`, as well as for the "backdrop" selector a block beneath, most of the issue already goes away. Then, you still need to remove the padding in the same block (in this example file on line 11117). Also notice that you may have to edit both the gtk.css *and* the gtk-dark.css.
