### ISSUE TITLE
Cinnamon Bad look

### ISSUE THREAD

**Issue by DanielRios549** [paullinuxthemer/Mc-OS-themes#6]
Is there something to do for a correct look of this theme on Cinnamon? I have all necessary packages installed, but the theme don't work properly...

**Comment by AceThaGemini** [comment]
I wouldn't call it a bad look. I was about to hit "New issue" button and request for a Cinnamon support. All themes created by @paullinuxthemer are so beautiful, so I decide to give them a short. But the support for Cinnamon is kinda poor if not not-there-at-all. Any Cinnamon user would understand what I'm about to say here. In my case, only "Controls" option works, unfortunately "Windows borders" and "Desktop" options doesn't work in Theme editor (the default theme editor in Cinnamon).

I'm on LM 19 with Cinnamon 3.8.6.

**Comment by DanielRios549** [comment]
I thought that the theme works on all GTK interfaces, because it is a GTK theme...

**Comment by paullinuxthemer** [comment]
The theme is only designed to be used in a pure gnome desktop. And gtk 3.20+ only.  I never incorporated any code for cinnamon, because it wouldn't work on Linux mint ( their supported only up to 3.18) cinnamon uses its own windowmanager and filemanager. I have not tested it with the latest mint-version. But it would still require a sizeable amount of work to make it work properly.

**Comment by DanielRios549** [comment]
Ok man, it is explained now, it was my fault, as I said, I thought it works on all GTK interfaces, at least for the GTK, not for desktop or shell
